apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-app-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rag-app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-ui
      protocol: TCP
      name: http
  selector:
    {{- include "rag-app-chart.selectorLabels" . | nindent 4 }}