---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fileserver.subdomain }}-fileserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fileserver.subdomain }}-fileserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.fileserver.subdomain }}-fileserver
  template:
    metadata:
      labels:
        app: {{ .Values.fileserver.subdomain }}-fileserver
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: {{ .Values.fileserver.subdomain }}-fileserver
          image: python:3.12-alpine
          command: ["python", "-m", "http.server", "8082", "--directory", "/mnt"]
          ports:
            - containerPort: 8082
          volumeMounts:
            - name: shared
              mountPath: /mnt
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: kubeflow-shared-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fileserver.subdomain }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fileserver.subdomain }}-fileserver
spec:
  selector:
    app: {{ .Values.fileserver.subdomain }}-fileserver
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  type: ClusterIP

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.fileserver.subdomain }}-fileserver-vs
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ printf "%s.%s" .Values.fileserver.subdomain .Values.domainName }}
  gateways:
    - istio-system/ezaf-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ printf "%s-service.%s.svc.cluster.local" .Values.fileserver.subdomain .Release.Namespace }}
            port:
              number: 8082
