apiVersion: v2
name: vision-analytics
description: A Helm chart for Visual Analytics Studio on HPE PCAI.
type: application

# This is the chart version. This is incremented for chart changes.
version: 0.1.2

# This is the version number of the application being deployed.
appVersion: "0.0.2"
