apiVersion: v2
name: rag-app-chart
description: A Helm chart for deploying the rag app with a Gradio UI.
type: application

# This is the chart version.
version: "0.0.1"

# This is the version number of the application being deployed.
appVersion: "0.0.1"